spring.application.name=Actividad Formativa BD FFEOE - RA4

server.port=8089

spring.datasource.url=jdbc:mariadb://localhost:3308/partes_trabajo_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
